version: '3'

services: 
 
  
  mysql:
    image: mysql:5.7
    container_name: wordpress_db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wordpress_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass      
    volumes:
      - db_data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wordpress_phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql  
  
  wordpress:
    image: wordpress:latest
    container_name: wordpress_app
    ports:
      - 8000:80
    environment:
      - WORDPRESS_DB_USER=user
      - WORDPRESS_DB_PASSWORD=pass
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_NAME=wordpress_db
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mysql

volumes: 
  db_data:
  wordpress_data: